// data.js
export const surveyData = {
  Zambia: [
    {
      category: "Data Collection",
      Water: "50%",
      Sanitation: "50%",
      Finance: "50%",
      Regulation: "50%",
      "Utility Operations": "50%",
    },
    {
      category: "Data ownership & Management",
      Water: "25%",
      Sanitation: "25%",
      Finance: "25%",
      Regulation: "25%",
      "Utility Operations": "25%",
    },
    {
      category: "Data openness & Flow",
      Water: "33%",
      Sanitation: "33%",
      Finance: "33%",
      Regulation: "33%",
      "Utility Operations": "33%",
    },
    {
      category: "Data quality",
      Water: "25%",
      Sanitation: "25%",
      Finance: "25%",
      Regulation: "25%",
      "Utility Operations": "25%",
    },
    {
      category: "Data use",
      Water: "13%",
      Sanitation: "13%",
      Finance: "13%",
      Regulation: "13%",
      "Utility Operations": "13%",
    },
  ],
  Burundi: [
    {
      category: "Data Collection",
      Water: "60%",
      Sanitation: "60%",
      Finance: "60%",
      Regulation: "60%",
      "Utility Operations": "60%",
    },
    {
      category: "Data ownership & Management",
      Water: "30%",
      Sanitation: "30%",
      Finance: "30%",
      Regulation: "30%",
      "Utility Operations": "30%",
    },
    {
      category: "Data openness & Flow",
      Water: "40%",
      Sanitation: "40%",
      Finance: "40%",
      Regulation: "40%",
      "Utility Operations": "40%",
    },
    {
      category: "Data quality",
      Water: "20%",
      Sanitation: "20%",
      Finance: "20%",
      Regulation: "20%",
      "Utility Operations": "20%",
    },
    {
      category: "Data use",
      Water: "15%",
      Sanitation: "15%",
      Finance: "15%",
      Regulation: "15%",
      "Utility Operations": "15%",
    },
  ],
  Uganda: [
    {
      category: "Data Collection",
      Water: "70%",
      Sanitation: "70%",
      Finance: "70%",
      Regulation: "70%",
      "Utility Operations": "70%",
    },
    {
      category: "Data ownership & Management",
      Water: "35%",
      Sanitation: "35%",
      Finance: "35%",
      Regulation: "35%",
      "Utility Operations": "35%",
    },
    {
      category: "Data openness & Flow",
      Water: "45%",
      Sanitation: "45%",
      Finance: "45%",
      Regulation: "45%",
      "Utility Operations": "45%",
    },
    {
      category: "Data quality",
      Water: "25%",
      Sanitation: "25%",
      Finance: "25%",
      Regulation: "25%",
      "Utility Operations": "25%",
    },
    {
      category: "Data use",
      Water: "20%",
      Sanitation: "20%",
      Finance: "20%",
      Regulation: "20%",
      "Utility Operations": "20%",
    },
  ],
};
